export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ITEM_REPOSITORY = 'ITEM_REPOSITORY';
export const GROUP_REPOSITORY = 'GROUP_REPOSITORY';

export const COLUMN_REPOSITORY = 'COLUMN_REPOSITORY';
export const COLUMNVALUE_REPOSITORY = 'COLUMNVALUE_REPOSITORY';
export const COLUMNDROPDOWN_REPOSITORY = 'COLUMNDROPDOWN_REPOSITORY';
export const COLUMNPEOPLE_REPOSITORY = 'COLUMNPEOPLE_REPOSITORY';
export const COLUMNSTATUS_REPOSITORY = 'COLUMNSTATUS_REPOSITORY';

export const DEFAULTCOLUMN_REPOSITORY = 'DEFAULTCOLUMN_REPOSITORY';
export const DEFAULTCOLUMNDROPDOWN_REPOSITORY = 'DEFAULTCOLUMNDROPDOWN_REPOSITORY';
export const DEFAULTCOLUMNPEOPLE_REPOSITORY = 'DEFAULTCOLUMNPEOPLE_REPOSITORY';
export const DEFAULTCOLUMNSTATUS_REPOSITORY = 'DEFAULTCOLUMNSTATUS_REPOSITORY';

export const DROPDOWN_REPOSITORY = 'DROPDOWN_REPOSITORY';
export const DROPDOWNVALUES_REPOSITORY = 'DROPDOWNVALUES_REPOSITORY';
export const ROW_REPOSITORY = 'ROW_REPOSITORY';
export const STATUS_REPOSITORY = 'STATUS_REPOSITORY';
export const STATUSVALUE_REPOSITORY = 'STATUSVALUE_REPOSITORY';

export const INVITATION_REPOSITORY = 'INVITATION_REPOSITORY';
export const INVITATIONITEM_REPOSITORY = 'INVITATION_REPOSITORY';

export const SORT_REPOSITORY = 'SORT_REPOSITORY';
export const FILTER_REPOSITORY = 'FILTER_REPOSITORY';

export const PERMISSION_REPOSITORY = 'PERMISSION_REPOSITORY';

export const CHART_REPOSITORY = 'CHART_REPOSITORY';
export const CHARTSETTING_REPOSITORY = 'CHARTSETTING_REPOSITORY';
export const CHARTSETTINGGROUP_REPOSITORY = 'CHARTSETTINGGROUP_REPOSITORY';
export const CHARTCATEGORY_REPOSITORY = 'CHARTCATEGORY_REPOSITORY';
export const CHARTTYPE_REPOSITORY = 'CHARTTYPE_REPOSITORY';

export const BENCHMARK_REPOSITORY = 'BENCHMARK_REPOSITORY';


