export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ITEM_REPOSITORY = 'ITEM_REPOSITORY';
export const GROUP_REPOSITORY = 'GROUP_REPOSITORY';
export const DEFAULTCOLUMN_REPOSITORY = 'DEFAULTCOLUMN_REPOSITORY';
export const COLUMN_REPOSITORY = 'COLUMN_REPOSITORY';
export const DEFAULTCOLUMNDROPDOWN_REPOSITORY = 'DEFAULTCOLUMNDROPDOWN_REPOSITORY';
export const DEFAULTCOLUMNPEOPLE_REPOSITORY = 'DEFAULTCOLUMNPEOPLE_REPOSITORY';
export const DEFAULTCOLUMNSTATUS_REPOSITORY = 'DEFAULTCOLUMNSTATUS_REPOSITORY';
export const DROPDOWN_REPOSITORY = 'DROPDOWN_REPOSITORY';
export const DROPDOWNVALUES_REPOSITORY = 'DROPDOWNVALUES_REPOSITORY';
export const ROW_REPOSITORY = 'ROW_REPOSITORY';
export const STATUS_REPOSITORY = 'STATUS_REPOSITORY';
export const STATUSVALUE_REPOSITORY = 'STATUSVALUE_REPOSITORY';


